[build]
  command = "npm run build"
  publish = ".next"
 functions = "functions"
[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false